# Tarea 03 — Procesamiento de Datos con Pandas

**Instrucciones:** Completa cada celda de código con tu respuesta.  
Trabajarás con el dataset del Titanic para practicar transformaciones reales.

In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

---
## Parte 1 — Exploración y selección

**P1.** Imprime los nombres de todas las columnas y el número total de filas y columnas del DataFrame.

In [5]:
from IPython.display import display

tabla_columnas = pd.DataFrame({"Columnas": df.columns})
tabla_dimensiones = pd.DataFrame({"Filas": [df.shape[0]], "Columnas": [df.shape[1]]})

display(tabla_columnas)
display(tabla_dimensiones)

       Columnas
0   PassengerId
1      Survived
2        Pclass
3          Name
4           Sex
5           Age
6         SibSp
7         Parch
8        Ticket
9          Fare
10        Cabin
11     Embarked

   Filas  Columnas
0    891        12

**P2.** Usa `.loc` para seleccionar las filas 10 a 15 (inclusive) y solo las columnas `Name`, `Age` y `Survived`.

In [8]:
df.loc[10:15, ["Name", "Age", "Survived"]]

                                    Name   Age  Survived
10       Sandstrom, Miss. Marguerite Rut   4.0         1
11              Bonnell, Miss. Elizabeth  58.0         1
12        Saundercock, Mr. William Henry  20.0         0
13           Andersson, Mr. Anders Johan  39.0         0
14  Vestrom, Miss. Hulda Amanda Adolfina  14.0         0
15      Hewlett, Mrs. (Mary D Kingcome)   55.0         1

---
## Parte 2 — Valores nulos y limpieza

**P3.** Cuenta cuántos valores nulos hay en cada columna. ¿Cuáles columnas tienen nulos?

In [ ]:
nulos_por_columna = df.isnull().sum()
columnas_con_nulos = nulos_por_columna[nulos_por_columna > 0]

print(columnas_con_nulos.index.tolist())
columnas_con_nulos

['Age', 'Cabin', 'Embarked']

Age         177
Cabin       687
Embarked      2
dtype: int64

**Respuesta:** Las columnas con valores nulos son: Age, Cabin y Embarked.

**P4.** Rellena los valores nulos de la columna `Age` con la **mediana** de esa columna.  
Verifica que ya no haya nulos en `Age`.

In [12]:
mediana_age = df["Age"].median()
df["Age"] = df["Age"].fillna(mediana_age)

print("Nulos en Age después del relleno:", df["Age"].isnull().sum())

Nulos en Age después del relleno: 0

---
## Parte 3 — Nuevas columnas y agrupaciones

**P5.** Crea una nueva columna llamada `FamilySize` que sea la suma de `SibSp` + `Parch` + 1 (el pasajero mismo).

In [13]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

**P6.** Usando `groupby`, calcula la **tasa de supervivencia promedio** (columna `Survived`) por clase (`Pclass`).  
¿Qué clase tuvo mayor probabilidad de sobrevivir?

In [14]:
supervivencia_por_clase = df.groupby("Pclass")["Survived"].mean()

print(supervivencia_por_clase)
print("La clase con mayor supervivencia fue:", supervivencia_por_clase.idxmax())

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64
La clase con mayor supervivencia fue: 1

**P7.** Calcula la edad promedio y la tarifa (`Fare`) promedio, agrupando por `Sex` y `Pclass`.  
Usa `.groupby()` con `.agg()`.

In [15]:
resumen = (
    df.groupby(["Sex", "Pclass"])
    .agg({"Age": "mean", "Fare": "mean"})
    .rename(columns={"Age": "Edad_promedio", "Fare": "Tarifa_promedio"})
)

resumen

               Edad_promedio  Tarifa_promedio
Sex    Pclass
female 1           33.978723       106.125798
       2           28.703947        21.970121
       3           23.572917        16.118810
male   1           38.995246        67.226127
       2           30.512315        19.741782
       3           26.911873        12.661633

---
## Parte 4 — Ordenamiento y duplicados

**P8.** Ordena el DataFrame por `Fare` de mayor a menor y muestra las primeras 5 filas.  
¿Cuánto pagó el pasajero más caro?

In [16]:
df_ordenado = df.sort_values(by="Fare", ascending=False)

df_ordenado.head()

print("El pasajero más caro pagó:", df_ordenado["Fare"].iloc[0])

El pasajero más caro pagó: 512.3292

**P9.** Verifica si hay filas duplicadas en el DataFrame. ¿Cuántas hay?

In [17]:
duplicadas = df.duplicated().sum()
print("Cantidad de filas duplicadas:", duplicadas)
print("¿Hay filas duplicadas?", df.duplicated().any())
print("Cantidad de filas duplicadas:", df.duplicated().sum())

Cantidad de filas duplicadas: 0
¿Hay filas duplicadas? False
Cantidad de filas duplicadas: 0